name: CI

on: [push]

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Update image
      run: | 
        sudo apt-get update &&
        sudo apt -qq install git git-ftp
    - name: install git and stuff
      run: |
        git config git-ftp.url "ftp://178.128.108.88:21/public_html"
        git config git-ftp.user "${{ secrets.USERNAME }}"
        git config git-ftp.password "${{ secrets.PASSWORD }}"
        git ftp catchup ftp://178.128.108.88/web-port
        
