name: CI

on: [push]

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update image
      run: | 
        sudo apt-get update &&
        sudo apt-get -qq install git git-ftp
    - name: install git and stuff
      run: git ftp -v
        
