name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Update image
      run: | 
        sudo apt-get update &&
        sudo apt -qq install git git-ftp
    - name: install git and stuff
      run: |
        git ftp catchup -f --user ${{ secrets.USER }} --passwd ${{ secrets.PASSWORD }} ftp://178.128.108.88/web-port
        
